### ISSUE TITLE
女友盲盒插件用一段时间就报错

### ISSUE THREAD

**Issue by lumia1998** [MieMieMieeeee/koishi-gpt-girlfriend#4]
![Screenshot_20240528_202539](https://github.com/MieMieMieeeee/koishi-gpt-girlfriend/assets/63107956/40179c17-79d5-4ca7-8596-d1bf0adeb839)
卸载重装能解决但是过一段时间又这样了

**Comment by lumia1998** [comment]
首先前置插件三个，第一个 rrgpt 已经用不了了，第二个自己建造我也弄不了所以我用的 gpt  API 但是我没有官方的 API 所以把插件里的 API 地址改成第三方了，这样是可以用的。既然你说可能是前置 gpt 的问题，我测试下重启插件或者借一个官方 API 测试下效果

**Comment by MieMieMieeeee** [comment]
可以的话提供下第三方的地址我去瞅瞅怎么回事（如果可以免费体验的话...）

**Comment by lumia1998** [comment]
两个 api 都不行。。。
你可以先试试这个
https://github.com/chatanywhere/GPT_API_free?tab=readme-ov-file
症状就是用个十多次可以，之后就如我截图报错

**Comment by MieMieMieeeee** [comment]
自己试了十多次一下好像没什么问题呢（虽然好像回复的效果没有官方的好）

以下为@miemiemie/gpt-api的配置
![image](https://github.com/MieMieMieeeee/koishi-gpt-girlfriend/assets/34560903/8bc4c3c7-0c3b-47f1-abc0-21adaa1c336c)

另外可以尝试更新一下插件到最新版（虽然感觉旧版也应该没问题...）
- @miemiemie/gpt-api到0.1.7
- @miemiemie/gpt-girlfriend到0.3.13

**Comment by lumia1998** [comment]
我用的就是最新版，那我 白天再观察一下

**Comment by lumia1998** [comment]
![image](https://github.com/MieMieMieeeee/koishi-gpt-girlfriend/assets/63107956/debf1f6a-0d82-42ad-9628-17f584e4c270)
又出现了...

**Comment by lumia1998** [comment]
请求多了可能会出问题
要不加一个一分钟只能接受一次请求的设置?

**Comment by lumia1998** [comment]
大佬还是加群说吧
Koishi 非官方交流群
590104798

**Comment by MieMieMieeeee** [comment]
gpt服务问题，非本插件问题，关闭issue
