### ISSUE TITLE
未能识别push

### ISSUE THREAD

**Issue by ai2c** [MieMieMieeeee/koishi-gpt-girlfriend#7]
![QQ截图20240628141644](https://github.com/MieMieMieeeee/koishi-gpt-girlfriend/assets/17328013/a6bd5756-2d4b-48c8-9395-2dbffa9bca73)
![QQ截图20240628141655](https://github.com/MieMieMieeeee/koishi-gpt-girlfriend/assets/17328013/289fde30-140d-4338-8105-58282afc0119)
gpt可以正常使用，但提示“TypeError: Cannot read properties of undefined (reading 'push')”，是koishi更新到4.17.9才出现的。

**Comment by MieMieMieeeee** [comment]
@ai2c 
感谢投稿
刚刚更新的0.3.18版中修复了这个问题（才不是刚看到..）
